// <auto-generated />
using System;
using CookHomie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookHomie.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504053405_SeedRecipeBaselineData")]
    partial class SeedRecipeBaselineData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookHomie.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8109ce9-f967-4f32-a4a4-5031a0df1baf"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 1,
                            Name = "Milk",
                            Quantity = 1m,
                            Unit = "liter",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5a4b2996-ebf8-4b98-91fe-290ca2d9b2bd"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = true,
                            Location = 1,
                            Name = "Cheddar Cheese",
                            Quantity = 250m,
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4f80dd83-a339-45bb-9f24-d76cc0f25818"),
                            Category = "Produce",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 1,
                            Name = "Spinach",
                            Quantity = 1m,
                            Unit = "bag",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("680aef2a-9969-4346-95d0-c6fc9f426445"),
                            Category = "Produce",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 1,
                            Name = "Tomatoes",
                            Quantity = 6m,
                            Unit = "units",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fd769e8e-252a-4e14-b0ec-87a5f4baa253"),
                            Category = "Protein",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 2,
                            Name = "Chicken Breast",
                            Quantity = 2m,
                            Unit = "units",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("933d0ce1-faad-4a4b-b349-1d9f60dbb0be"),
                            Category = "Protein",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 0,
                            Name = "Canned Tuna",
                            Quantity = 3m,
                            Unit = "cans",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6f06cae-72f7-4bc2-bf16-58b7d24924fe"),
                            Category = "Grains",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 0,
                            Name = "Rice",
                            Quantity = 2m,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f92ff908-beb0-4af0-90d9-5992a39cc0bc"),
                            Category = "Grains",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 0,
                            Name = "Pasta",
                            Quantity = 4m,
                            Unit = "packs",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 1,
                            Name = "Eggs",
                            Quantity = 12m,
                            Unit = "units",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 1,
                            Name = "Butter",
                            Quantity = 200m,
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Produce",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 0,
                            Name = "Garlic",
                            Quantity = 1m,
                            Unit = "head",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Pantry",
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpened = false,
                            Location = 0,
                            Name = "Olive Oil",
                            Quantity = 500m,
                            Unit = "ml",
                            UpdatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CookMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CookMinutes = 20,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Boil pasta until al dente. In a saucepan, melt butter over medium heat. Stir in flour and cook 1 minute. Gradually whisk in milk and cook until thickened. Remove from heat, stir in cheddar until melted. Combine sauce with pasta, season with salt and pepper. Serve hot.",
                            Name = "Classic Mac & Cheese",
                            PrepMinutes = 10,
                            Tags = new[] { "comfort", "quick", "vegetarian" }
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CookMinutes = 20,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Preheat oven to 200°C. Cook pasta until al dente. Drain tuna. In a large bowl, mix pasta, tuna, tomatoes, and half the cheese. Transfer to a baking dish, top with remaining cheese. Bake 20 minutes until golden and bubbly.",
                            Name = "Tuna Pasta Bake",
                            PrepMinutes = 15,
                            Tags = new[] { "baked", "protein", "family-friendly" }
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CookMinutes = 8,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Beat eggs in a bowl with a splash of milk, salt, and pepper. Melt butter in a non-stick pan over medium-low heat. Add eggs and gently stir with a spatula. When nearly set, fold in spinach and cook 1 more minute. Serve immediately.",
                            Name = "Spinach & Egg Scramble",
                            PrepMinutes = 5,
                            Tags = new[] { "breakfast", "quick", "vegetarian" }
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CookMinutes = 15,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Cook rice and let it cool (day-old rice works best). Scramble eggs and set aside. Heat oil in a wok over high heat. Stir-fry onion and garlic 1 minute. Add chicken and cook through. Add rice, soy sauce, and eggs. Toss everything together over high heat until well combined.",
                            Name = "Chicken Fried Rice",
                            PrepMinutes = 15,
                            Tags = new[] { "asian", "wok", "meal-prep" }
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CookMinutes = 15,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Cook pasta in salted boiling water. Meanwhile, heat olive oil in a pan and sauté garlic until fragrant. Add tomatoes and cook 10 minutes, crushing them lightly. Toss drained pasta with the sauce, adjust seasoning. Serve with fresh herbs if available.",
                            Name = "Simple Tomato Pasta",
                            PrepMinutes = 5,
                            Tags = new[] { "quick", "vegan", "simple" }
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CookMinutes = 10,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Drain tuna and flake into a bowl. Hard boil eggs and chop. Mix tuna, eggs, cheddar, and onion. Add mayonnaise and stir until combined. Season to taste. Serve on bread with lettuce.",
                            Name = "Classic Tuna Sandwich",
                            PrepMinutes = 15,
                            Tags = new[] { "lunch", "sandwich", "protein" }
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CookMinutes = 20,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Instructions = "Season chicken breast with salt and pepper. Melt butter in a skillet over medium-high heat. Cook chicken 5-7 minutes per side until golden and cooked through. In the last minute, add garlic and baste chicken. Rest 5 minutes, slice. Serve over steamed rice with pan juices drizzled on top.",
                            Name = "Garlic Butter Chicken with Rice",
                            PrepMinutes = 10,
                            Tags = new[] { "protein", "garlic", "family-friendly" }
                        });
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1010101-0101-0101-0101-010101010101"),
                            IngredientName = "Pasta",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Unit = "packs"
                        },
                        new
                        {
                            Id = new Guid("a1010101-0101-0101-0101-010101010102"),
                            IngredientName = "Cheddar Cheese",
                            IsOptional = false,
                            Quantity = 200m,
                            RecipeId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a1010101-0101-0101-0101-010101010103"),
                            IngredientName = "Butter",
                            IsOptional = false,
                            Quantity = 50m,
                            RecipeId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a1010101-0101-0101-0101-010101010104"),
                            IngredientName = "Milk",
                            IsOptional = false,
                            Quantity = 1m,
                            RecipeId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Unit = "liter"
                        },
                        new
                        {
                            Id = new Guid("a2020202-0202-0202-0202-020202020201"),
                            IngredientName = "Pasta",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Unit = "packs"
                        },
                        new
                        {
                            Id = new Guid("a2020202-0202-0202-0202-020202020202"),
                            IngredientName = "Canned Tuna",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Unit = "cans"
                        },
                        new
                        {
                            Id = new Guid("a2020202-0202-0202-0202-020202020203"),
                            IngredientName = "Cheddar Cheese",
                            IsOptional = false,
                            Quantity = 150m,
                            RecipeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a2020202-0202-0202-0202-020202020204"),
                            IngredientName = "Tomatoes",
                            IsOptional = false,
                            Quantity = 4m,
                            RecipeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a3030303-0303-0303-0303-030303030301"),
                            IngredientName = "Eggs",
                            IsOptional = false,
                            Quantity = 4m,
                            RecipeId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a3030303-0303-0303-0303-030303030302"),
                            IngredientName = "Spinach",
                            IsOptional = false,
                            Quantity = 1m,
                            RecipeId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Unit = "bag"
                        },
                        new
                        {
                            Id = new Guid("a3030303-0303-0303-0303-030303030303"),
                            IngredientName = "Butter",
                            IsOptional = false,
                            Quantity = 30m,
                            RecipeId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a3030303-0303-0303-0303-030303030304"),
                            IngredientName = "Onion",
                            IsOptional = true,
                            Quantity = 1m,
                            RecipeId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a4040404-0404-0404-0404-040404040401"),
                            IngredientName = "Rice",
                            IsOptional = false,
                            Quantity = 1m,
                            RecipeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("a4040404-0404-0404-0404-040404040402"),
                            IngredientName = "Chicken Breast",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a4040404-0404-0404-0404-040404040403"),
                            IngredientName = "Eggs",
                            IsOptional = false,
                            Quantity = 3m,
                            RecipeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a4040404-0404-0404-0404-040404040404"),
                            IngredientName = "Onion",
                            IsOptional = false,
                            Quantity = 1m,
                            RecipeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a4040404-0404-0404-0404-040404040405"),
                            IngredientName = "Garlic",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("a5050505-0505-0505-0505-050505050501"),
                            IngredientName = "Pasta",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Unit = "packs"
                        },
                        new
                        {
                            Id = new Guid("a5050505-0505-0505-0505-050505050502"),
                            IngredientName = "Tomatoes",
                            IsOptional = false,
                            Quantity = 6m,
                            RecipeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a5050505-0505-0505-0505-050505050503"),
                            IngredientName = "Garlic",
                            IsOptional = false,
                            Quantity = 4m,
                            RecipeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("a5050505-0505-0505-0505-050505050504"),
                            IngredientName = "Olive Oil",
                            IsOptional = false,
                            Quantity = 3m,
                            RecipeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = new Guid("a6060606-0606-0606-0606-060606060601"),
                            IngredientName = "Canned Tuna",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Unit = "cans"
                        },
                        new
                        {
                            Id = new Guid("a6060606-0606-0606-0606-060606060602"),
                            IngredientName = "Eggs",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a6060606-0606-0606-0606-060606060603"),
                            IngredientName = "Cheddar Cheese",
                            IsOptional = false,
                            Quantity = 50m,
                            RecipeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a6060606-0606-0606-0606-060606060604"),
                            IngredientName = "Onion",
                            IsOptional = true,
                            Quantity = 1m,
                            RecipeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a7070707-0707-0707-0707-070707070701"),
                            IngredientName = "Chicken Breast",
                            IsOptional = false,
                            Quantity = 2m,
                            RecipeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Unit = "units"
                        },
                        new
                        {
                            Id = new Guid("a7070707-0707-0707-0707-070707070702"),
                            IngredientName = "Butter",
                            IsOptional = false,
                            Quantity = 60m,
                            RecipeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a7070707-0707-0707-0707-070707070703"),
                            IngredientName = "Garlic",
                            IsOptional = false,
                            Quantity = 3m,
                            RecipeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("a7070707-0707-0707-0707-070707070704"),
                            IngredientName = "Rice",
                            IsOptional = false,
                            Quantity = 1m,
                            RecipeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.ShoppingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBought")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedRecipeId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CookHomie.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.ShoppingItem", b =>
                {
                    b.HasOne("CookHomie.Domain.Entities.Recipe", "LinkedRecipe")
                        .WithMany()
                        .HasForeignKey("LinkedRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedRecipe");
                });

            modelBuilder.Entity("CookHomie.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
