// <auto-generated />
using System;
using CookHomie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookHomie.Infrastructure.Migrations;

/// <inheritdoc />
[DbContext(typeof(AppDbContext))]
[Migration("20260426000001_InitialCreate")]
partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CookHomie.Domain.Entities.InventoryItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("timestamp with time zone");

                b.Property<DateOnly>("ExpiresAt")
                    .HasColumnType("date");

                b.Property<bool>("IsOpened")
                    .HasColumnType("boolean");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Quantity")
                    .HasColumnType("numeric");

                b.Property<string>("Notes")
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .IsRequired()
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("InventoryItems");
            });

        modelBuilder.Entity("CookHomie.Domain.Entities.Recipe", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("CookMinutes")
                    .HasColumnType("integer");

                b.Property<string>("Instructions")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string[]>("Tags")
                    .HasColumnType("text[]");

                b.Property<int>("PrepMinutes")
                    .HasColumnType("integer");

                b.Property<string>("Source")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Recipes");
            });

        modelBuilder.Entity("CookHomie.Domain.Entities.RecipeIngredient", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("RecipeId")
                    .HasColumnType("uuid");

                b.Property<string>("IngredientName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Quantity")
                    .HasColumnType("numeric");

                b.Property<bool>("IsOptional")
                    .HasColumnType("boolean");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("RecipeId");

                b.ToTable("RecipeIngredients");
            });

        modelBuilder.Entity("CookHomie.Domain.Entities.ShoppingItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsBought")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("LinkedRecipeId")
                    .HasColumnType("uuid");

                b.Property<int>("Priority")
                    .HasColumnType("integer");

                b.Property<decimal?>("Quantity")
                    .HasColumnType("numeric");

                b.Property<string>("Unit")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("LinkedRecipeId");

                b.ToTable("ShoppingItems");
            });

        modelBuilder.Entity("CookHomie.Domain.Entities.RecipeIngredient", b =>
            {
                b.HasOne("CookHomie.Domain.Entities.Recipe", "Recipe")
                    .WithMany("Ingredients")
                    .HasForeignKey("RecipeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Recipe");
            });

        modelBuilder.Entity("CookHomie.Domain.Entities.ShoppingItem", b =>
            {
                b.HasOne("CookHomie.Domain.Entities.Recipe", "LinkedRecipe")
                    .WithMany()
                    .HasForeignKey("LinkedRecipeId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .IsRequired(false);

                b.Navigation("LinkedRecipe");
            });
#pragma warning restore 612, 618
    }
}