import { describe, expect, it } from "vitest";
import { getRecipes, getRecipeById, addRecipe } from "../server/utils/recipeStore";

describe("recipeStore", () => {
  it("getRecipes returns array", () => {
    const recipes = getRecipes();
    expect(Array.isArray(recipes)).toBe(true);
    expect(recipes.length).toBeGreaterThan(0);
  });

  it("getRecipeById returns recipe or undefined", () => {
    const r = getRecipeById("r1");
    expect(r?.name).toBe("Classic Pancakes");
    expect(getRecipeById("nonexistent")).toBeUndefined();
  });

  it("addRecipe returns recipe with new id", () => {
    const before = getRecipes().length;
    const newR = addRecipe({ name: "Test", instructions: "Test", prepMinutes: 1, cookMinutes: 1, tags: [], ingredients: [] });
    expect(newR.id).toBeTruthy();
    expect(getRecipes().length).toBe(before + 1);
  });

  it("addRecipe persists ingredients when provided", () => {
    const ingredientInput = [
      { ingredientName: "flour", quantity: 200, unit: "g", isOptional: false },
    ];

    const newR = addRecipe({
      name: "Test Recipe with Ingredients",
      instructions: "Test instructions",
      prepMinutes: 1,
      cookMinutes: 1,
      tags: [],
      ingredients: ingredientInput
    });

    expect(newR.ingredients).toHaveLength(1);
    expect(newR.ingredients[0].ingredientName).toBe("flour");
    expect(newR.ingredients[0].quantity).toBe(200);
    expect(newR.ingredients[0].unit).toBe("g");
    expect(newR.ingredients[0].isOptional).toBe(false);
    // ID and recipeId are generated by addRecipe
    expect(newR.ingredients[0].id).toBeTruthy();
    expect(newR.ingredients[0].recipeId).toBe(newR.id);
  });
});
